### ISSUE TITLE
Feature Request - Add option for RAMDisk

### ISSUE THREAD

**Issue by derrickmehaffy** [AllTheMods/ServerStarter#1]
Not sure how viable this will be on Windows as I've never attempted it there. However I feel it would be a nice option to add the ability to setup a ram disk using the start script (along with the cron flush to disk)

Its been some time since I've run a server but I believe ram disks can still provide a useful benefit (correct me if I'm wrong)

Being able to define a custom directory and maybe provide some small documentation on setting up the `/etc/fstab` file might be a good idea as well.

I believe at the very least offering the ability to configure a ram disk may help with some of the larger servers and world gen lag (if the world hasn't been pre-gen'ed)

Sorry if this has been suggested before, I didn't see any other closed issues in this (seems this start system is new?)

Side note, awesome job on this, like I said its been a while since I've ran a server and this script/jar made it extremely easy to install ATM3. :smiley:

**Comment by BloodWorkXGaming** [comment]
I have never worked with ram disks myself, and I have no idea how well they work with MC, or even less I don't know how viable it is to start one from inside java.

Does the JVM also need to run inside the RamDisk? Does Java/MC seamlessly integrate with it or are there hickups?
What happens if you run out of RamDisk space? Like our ATM3 server had a 9 gb world file in zipped form, therefore you would need a quite large ramdisk.

But I do agree, it might help in some cases, if you have the knowledge how to do it (maybe even cross platform) I would gladly accept a PR for it.

**Comment by derrickmehaffy** [comment]
@BloodWorkXGaming Generally speaking (and my knowledge is also quite limited on the subject) 

Basically on Linux you would create the ram-disk, mount it to a location, and symlink that location to your minecraft `world` folder. Then create the `world-disk` folder and every few seconds/minutes/ect "flush" the files from the `world` folder to the `world-disk` folder.

Obviously there are some commands that need to be run on startup and shutdown to sync the two. 

I'll keep looking into it and see if there is a viable way to do this here, I've seen other scripts that do this but not sure how easy it is to tie into here.

**Comment by martmists** [comment]
RAM disks do make working with the `world` folder interactions much faster, so if this turns out to be possible it's a +1 from me.

**Comment by derrickmehaffy** [comment]
I'm hoping it would with some of the world-gen latency especially with plugins like twilight forest (RIP my hard drives).

**Comment by martmists** [comment]
@BloodWorkXGaming Feel free to close this
